# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_items', '0002_auto_20160224_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='dplussession',
            name='directory',
        ),
        migrations.RemoveField(
            model_name='dplussession',
            name='job_running',
        ),
        migrations.RemoveField(
            model_name='dplussession',
            name='most_recent_calc',
        ),
        migrations.RemoveField(
            model_name='dplussession',
            name='process_handle',
        ),
        migrations.AddField(
            model_name='dplussession',
            name='job',
            field=models.CharField(blank=True, default=None, max_length=4096, null=True),
        ),
        migrations.DeleteModel(
            name='Calculation',
        ),
    ]
